provider: cloudflare
auth:
  cloudflare:
    token: CLOUDFLARE_TOKEN
    #
    # Other arguments of cloudflare-python
    # class constructor are supported, e.g auth using email:
    #
    # email: test@example.com

replace:
  a:
    - from: 127.0.0.1
      to: 127.0.0.2

  aaaa:
    - from: ::1
      to: ::2
      ttl: 120

  cname:
    - from: old.cname.example.com
      to: new.cname.example.com
